### ISSUE TITLE
DBConnection.ConnectionError :token

### ISSUE THREAD

**Issue by dougalcorn** [erlangbureau/jamdb_oracle#37] opened 2018-01-02 21:27 UTC
I'm getting this stack trace in production of my phoenix app:

```
** (exit) an exception was raised:
    ** (DBConnection.ConnectionError) :token
        (jamdb_oracle) lib/jamdb_oracle_ecto.ex:166: Ecto.Adapters.Jamdb.Oracle.Connection.error!/1
        (ecto) lib/ecto/adapters/sql.ex:256: Ecto.Adapters.SQL.sql_call/6
        (client_compass) lib/client_compass/repo.ex:13: ClientCompass.Repo.nextval/1
        (client_compass) lib/web_ca/odometer_reading.ex:28: WebCa.OdometerReading.changeset/1
        (client_compass) lib/client_compass_web/controllers/odo_readings_controller.ex:64: ClientCompassWeb.OdoReadingsController.create/2
```

I've implemented `nextval` on my `Repo` like so:

```elixir
  def nextval(sequence) do
    case query("SELECT WEB_CA.#{sequence}.nextval from dual") do
      {:ok, %{columns: ["NEXTVAL"], num_rows: 1, rows: [[next_id]]}} -> next_id
    end
  end
```

All of my Ecto modules have their own sequence and call `nextval` to get the unique primary key before inserting. We've written tests around this and it behaves reliably. We've used this in production with jamdb v0.1.0 with no errors. After upgrading to jamdb v0.1.1, we have intermittent errors as above. It's hard to describe the frequency as I don't have hard statistics. My estimation at this point is we're getting the above error about 1 out of 50 calls.  I have one user who triggered the error, re-submitted and triggered the error again, then re-submitted a third time and it worked fine. 

This piece of our code hasn't changed, yet we're seeing these new errors. We're looking for help figuring out how to work on this.

**Comment by vstavskyi** [comment] 2018-01-03 09:42
I think it was broken only in 0.1.1 and was fixed in 0.1.2 at [line 77](https://github.com/erlangbureau/jamdb_oracle/commit/09c9b21e76be5a2dff32f4bf1cc58d6e0f41e011)

**Comment by dougalcorn** [comment] 2018-01-03 13:51
That's cool. Can you help me understand what's happening? I'm trying to understand the code, but can't.

**Comment by vstavskyi** [comment] 2018-01-04 22:23
I remembered only this major change between versions. This is most likely to be caused by another query.
With this [commit](https://github.com/erlangbureau/jamdb_oracle/commit/0be8cb82db5a2f14c60d123802bd043861f4df30)  we'll get additional token error data to analyze.

**Comment by dougalcorn** [comment] 2018-01-05 14:56
You're saying that a previous query is causing this nextval query to fail in some way?

**Comment by vstavskyi** [comment] 2018-01-05 22:14
It can be network delay problem or database cannot manаge with the load or driver cannot decode database response ( unknown token ). Tcpdump and token error data will show more.

I can offer a slightly complicated version of your function:
```
defp nextval(sequence) do
 case query("BEGIN SELECT WEB_CA.#{sequence}.nextval into :1 from dual; END;", [out: 0]) do
   {:ok, %{rows: [[next_id]]}} -> next_id
 end
end
```

Or you can get several ids at once:
```
def nextval(sequence, count) do
 case query("SELECT WEB_CA.#{sequence}.nextval from dual CONNECT BY LEVEL <= :1", [count]) do 
  {:ok, %{num_rows: count, rows: next_id_list}} -> next_id_list
 end
end
```

**Comment by vstavskyi** [comment] 2018-01-12 14:26
Have you tried Identity Columns in Oracle Database 12c already? [Article](https://oracle-base.com/articles/12c/identity-columns-in-oracle-12cr1)
Should I try to support them?

**Closed** 2018-02-09 14:07 UTC
