### ISSUE TITLE
oracle login error

### ISSUE THREAD

**Issue by chenyu468** [erlangbureau/jamdb_oracle#3] opened 2016-03-22 15:00 UTC
2016-03-22 22:32:10.931 [debug] |jamdb_oracle|jamdb_oracle_conn|recv|292|Undefined|Undefined|Undefined|Undefined|Undefined|Undefined|Undefined|_290:
        <<>>
        <<0,11,0,0,12,0,0,0,1,0,1>>
2016-03-22 22:32:10.931 [debug] |jamdb_oracle|jamdb_oracle_conn|recv|285|Undefined|Undefined|Undefined|Undefined|Undefined|Undefined|Undefined|_283:
        <<>>
2016-03-22 22:32:10.931 [debug] |jamdb_oracle|jamdb_oracle_conn|handle_login_resp|161|Undefined|Undefined|Undefined|Undefined|Undefined|Undefined|Undefined|_161:
        12
        <<1,0,1>>
2016-03-22 22:32:10.932 [error] |Undefined|Undefined|Undefined|Undefined|Undefined|Undefined|Undefined|Undefined|Undefined|Undefined|Undefined|CRASH REPORT Process <0.76.0> with 0 neighbours exited with reason: no match of right hand value login_failed in jamdb_oracle:init/1 line 37 in gen_server:init_it/6 line 330
** exception error: no match of right hand side value {error,{{badmatch,login_failed},
                                                              [{jamdb_oracle,init,1,
                                                                             [{file,"src/jamdb_oracle.erl"},{line,37}]},
                                                               {gen_server,init_it,6,[{file,"gen_server.erl"},{line,306}]},
                                                               {proc_lib,init_p_do_apply,3,
                                                                         [{file,"proc_lib.erl"},{line,237}]}]}}

**Comment by kostyushkin** [comment] 2016-03-22 15:14
duplicate of #2

**Closed** 2016-03-22 15:13 UTC
